version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/var/www/html"
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - "./mariadb/volume:/var/lib/mysql"